let data = [{
    "id": 521,
    "title": "Diablo Immortal",
    "thumbnail": "https://www.freetogame.com/g/521/thumbnail.jpg",
    "short_description": "Built for mobile and also released on PC, Diablo Immortal fills in the gaps between Diablo II and III in an MMOARPG environment.",
    "game_url": "https://www.freetogame.com/open/diablo-immortal",
    "genre": "MMOARPG",
    "platform": "PC (Windows)",
    "publisher": "Blizzard Entertainment",
    "developer": "Blizzard Entertainment",
    "release_date": "2022-06-02",
    "freetogame_profile_url": "https://www.freetogame.com/diablo-immortal"
},
{
    "id": 519,
    "title": "Space Punks",
    "thumbnail": "https://www.freetogame.com/g/519/thumbnail.jpg",
    "short_description": "Space Punks is a sci-fi co-op looter shooter with graphics and humor that will likely appeal to the Borderlands fans among us.",
    "game_url": "https://www.freetogame.com/open/space-punks",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "JAGEX",
    "developer": "Flying Wild Hog",
    "release_date": "2022-04-20",
    "freetogame_profile_url": "https://www.freetogame.com/space-punks"
},
{
    "id": 517,
    "title": "Lost Ark",
    "thumbnail": "https://www.freetogame.com/g/517/thumbnail.jpg",
    "short_description": "Smilegateu2019s free-to-play multiplayer ARPG is a massive adventure filled with lands waiting to be explored, people waiting to be met, and an ancient evil waiting to be destroyed.",
    "game_url": "https://www.freetogame.com/open/lost-ark",
    "genre": "ARPG",
    "platform": "PC (Windows)",
    "publisher": "Amazon Games",
    "developer": "Smilegate RPG",
    "release_date": "2022-02-11",
    "freetogame_profile_url": "https://www.freetogame.com/lost-ark"
},
{
    "id": 516,
    "title": "PUBG: BATTLEGROUNDS",
    "thumbnail": "https://www.freetogame.com/g/516/thumbnail.jpg",
    "short_description": "Get into the action in one of the longest running battle royale games PUBG Battlegrounds.",
    "game_url": "https://www.freetogame.com/open/pubg",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "KRAFTON, Inc.",
    "developer": "KRAFTON, Inc.",
    "release_date": "2022-01-12",
    "freetogame_profile_url": "https://www.freetogame.com/pubg"
},
{
    "id": 515,
    "title": "Halo Infinite",
    "thumbnail": "https://www.freetogame.com/g/515/thumbnail.jpg",
    "short_description": "For the first time ever, a free-to-play Halo experience is available in the form of Halo Infiniteu2019s multiplayer.",
    "game_url": "https://www.freetogame.com/open/halo-infinite",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Xbox Game Studios",
    "developer": "343 Industries",
    "release_date": "2021-11-15",
    "freetogame_profile_url": "https://www.freetogame.com/halo-infinite"
},
{
    "id": 427,
    "title": "Drakensang Online",
    "thumbnail": "https://www.freetogame.com/g/427/thumbnail.jpg",
    "short_description": "A free to play browser-based top-down hack-and-slash 3D MMORPG similar to games in the Diablo series.",
    "game_url": "https://www.freetogame.com/open/drakensang-online",
    "genre": "MMORPG",
    "platform": "Web Browser",
    "publisher": "Bigpoint",
    "developer": "Bigpoint",
    "release_date": "2011-08-08",
    "freetogame_profile_url": "https://www.freetogame.com/drakensang-online"
},
{
    "id": 522,
    "title": "Flyff Universe",
    "thumbnail": "https://www.freetogame.com/g/522/thumbnail.jpg",
    "short_description": "Get the full Flyff experience on any platform with the free-to-play browser-based MMORPG Flyff Universe.",
    "game_url": "https://www.freetogame.com/open/flyff-universe",
    "genre": "MMORPG",
    "platform": "Web Browser",
    "publisher": "Gala Lab",
    "developer": "Gala Lab",
    "release_date": "2022-06-14",
    "freetogame_profile_url": "https://www.freetogame.com/flyff-universe"
},
{
    "id": 508,
    "title": "Enlisted",
    "thumbnail": "https://www.freetogame.com/g/508/thumbnail.jpg",
    "short_description": "Get ready to command your own World War II military squad in Gaijin and Darkflow Softwareu2019s MMO squad-based shooter Enlisted. ",
    "game_url": "https://www.freetogame.com/open/enlisted",
    "genre": "Shooter",
    "platform": "PC (Windows)",
    "publisher": "Gaijin Entertainment",
    "developer": "Darkflow Software",
    "release_date": "2021-04-08",
    "freetogame_profile_url": "https://www.freetogame.com/enlisted"
},
{
    "id": 475,
    "title": "Genshin Impact",
    "thumbnail": "https://www.freetogame.com/g/475/thumbnail.jpg",
    "short_description": "If youu2019ve been looking for a game to scratch that open-world action RPG itch, one with perhaps a bit of Asian flair, then youu2019re going to want to check out miHoYou2019s Genshin Impact.",
    "game_url": "https://www.freetogame.com/open/genshin-impact",
    "genre": "Action RPG",
    "platform": "PC (Windows)",
    "publisher": "miHoYo",
    "developer": "miHoYo",
    "release_date": "2020-09-28",
    "freetogame_profile_url": "https://www.freetogame.com/genshin-impact"
},
{
    "id": 445,
    "title": "Dark Knight",
    "thumbnail": "https://www.freetogame.com/g/445/thumbnail.jpg",
    "short_description": "A browser-based fantasy MMOARPG wherein players take on the role of a devil hunter descended from the gods.",
    "game_url": "https://www.freetogame.com/open/dark-knight",
    "genre": "MMORPG",
    "platform": "Web Browser",
    "publisher": "Opogame",
    "developer": "Opogame",
    "release_date": "2019-08-06",
    "freetogame_profile_url": "https://www.freetogame.com/dark-knight"
}]

export default data;

